### ISSUE TITLE
Depth adjuster crashing after OpenCV error

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/depth_calibration#10]
When I launched `rocon_gocart`:

```
OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/matrix.cpp, line 323
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/matrix.cpp:323: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat

[...]
[FATAL] [1453893840.808152920]: Service call failed!
[gopher/sensor_3d_long_range/sensor_3d_long_range_nodelet_manager-53] process has died [pid 26227, exit code -6, cmd /opt/ros/indigo/lib/nodelet/nodelet manager __name:=sensor_3d_long_range_nodelet_manager __log:=/home/yujin/.ros/log/71bab26e-c4e8-11e5-a9d1-d0509978a4ea/gopher-sensor_3d_long_range-sensor_3d_long_range_nodelet_manager-53.log].
log file: /home/yujin/.ros/log/71bab26e-c4e8-11e5-a9d1-d0509978a4ea/gopher-sensor_3d_long_range-sensor_3d_long_range_nodelet_manager-53*.log
[gopher/sensor_3d_long_range/depth_adjuster-56] process has died [pid 26267, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load depth_calibration/depth_adjuster sensor_3d_long_range_nodelet_manager input_depth_raw:=uncalibrated_depth/image_raw output_depth_raw:=depth/image_raw input_camera_info:=uncalibrated_depth/camera_info output_camera_info_relay:=depth/camera_info __name:=depth_adjuster __log:=/home/yujin/.ros/log/71bab26e-c4e8-11e5-a9d1-d0509978a4ea/gopher-sensor_3d_long_range-depth_adjuster-56.log].
log file: /home/yujin/.ros/log/71bab26e-c4e8-11e5-a9d1-d0509978a4ea/gopher-sensor_3d_long_range-depth_adjuster-56*.log
```

Looks like it's related to the depth adjuster.

There are several seemingly helpful Q&As related to this error:
- http://answers.opencv.org/question/46506/opencv-error-assertion-failed/
- http://answers.opencv.org/question/21374/possible-solutions-for-opencv-assertion-error-problem/

Maybe there error is triggered somewhere around here: https://github.com/yujinrobot/depth_calibration/blob/indigo-devel/src/depth_adjuster.cpp#L277-L281

**Comment by AlexReimann** [comment]
So it was right at the launch?
Any idea if the robot was calibrated?
Was it reproducible?

**Comment by bit-pirate** [comment]
> So it was right at the launch?

Yes.

> Any idea if the robot was calibrated?

Don't remember.

> Was it reproducible?

Not reliably. Sometimes happens. Sometimes not.

**Comment by bit-pirate** [comment]
Just happened again:
- gocart202
- sensors calibrated for depth
- happend after rebooting the SBC and during the first launch of software (`rocon_gocart`)

As just discussed, the next step:
- check size of the incoming depth image stream
- skip image if size is wrong and send a warning to the ROS log.

**Comment by AlexReimann** [comment]
Just got it again, so it is still there. Running with gdb for now and trying to catch where it is thrown

**Comment by AlexReimann** [comment]
Could be the same problem I saw somewhere else: The subscription is done too early so that the callback gets triggered before the init function is fully executed.

I'll do some digging.

**Comment by AlexReimann** [comment]
Caught it, hope fully fine now :p
