### ISSUE TITLE
Post success/failure to konsole

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/depth_calibration#17]
In order to enable to user to easily recongise, if the the process finished successful or not.

**Comment by AlexReimann** [comment]
Instead of manual inspection in rviz? 
Might be a bit tricky.

**Comment by bit-pirate** [comment]
Yeah, I guessed so. In the long run this needs to be further automated. This issue however was about a clear notification that the process (including writing to a file) has finished successfully or failed.

**Comment by AlexReimann** [comment]
It finishes with

> [ WARN] [1478254286.004135769]: Saving calibration to camera_info/depth_calibration.yaml  
> [ INFO] [1478254286.089741575]: Saving finished.

I'll at a "All done, finished. But check the result..."

**Comment by bit-pirate** [comment]
And there will be a blood red error, if something fails?

**Comment by AlexReimann** [comment]
Yes it does that already (if the write on the file or the directory fails).

Added finished message with pr #18
